### ISSUE TITLE
Print-Hactoberfest2022

### ISSUE THREAD

**Issue by sritikamanjrekar** [sritikamanjrekar/Print-Hacktoberfest2022#4]
Print - "My name is yourname, I am Contributing in Hacktober Open Source Project".

Any language you can use(HTML, c++, c, java, etc) to print.

Add that code into a directory Language name, if the directory doesn't exist, create one and add the code file.

**Comment by ShivanshDengla** [comment]
Hey,
Can i work on this?
Thanks

**Comment by ShivanshDengla** [comment]
I made a pull request #6 for this, do let me know if anything else is needed

**Comment by roshan2152** [comment]
Hey, @sritikamanjrekar can you assign this to me?

**Comment by sritikamanjrekar** [comment]
> I made a pull request #6 for this, do let me know if anything else is needed

Merged!!!

**Comment by sritikamanjrekar** [comment]
> I made a pull request #6 for this, do let me know if anything else is needed

@ShivanshDengla Done!!

**Comment by sritikamanjrekar** [comment]
> Hey, @sritikamanjrekar can you assign this to me?

@roshan2152 yeah, you can contribute->follow the CONTRIBUTING.md file

**Comment by Aman0307** [comment]
@sritikamanjrekar I have made a PR for this issue. I am printing the required sentence in html. Please merge the PR.

**Comment by Saurabhk1975** [comment]
assign me this @sritikamanjrekar

**Comment by Hussain6** [comment]
Can you assign this to me
