### ISSUE TITLE
Contributing in the repository.

### ISSUE THREAD

**Issue by Pranjal360Agarwal** [sritikamanjrekar/Print-Hacktoberfest2022#40]

**Comment by Sushantkumarsingh01** [comment]
i love to contribute

**Comment by prakharjadaun** [comment]
@sritikamanjrekar Can you also assign this issue to me? 
I am looking forward to contribute in hacktoberfest 2022.

**Comment by Ravi-Tiwary03** [comment]
Can you also assign this issue to me?
I am looking forward to contribute in hacktob

**Comment by aditya10003** [comment]
@sritikamanjrekar Can you also assign this issue to me?
I am looking forward to contribute in hacktoberfest 2022.

**Comment by shruti-2412** [comment]
Can you please assign this to me?
I want to contribute to hacktoberfest 2022

**Comment by falguni300103** [comment]
Can you please assign this issue to me? @sritikamanjrekar

**Comment by Rishi0510** [comment]
Can you please assign me this issue under Hacktoberfest? @sritikamanjrekar

**Comment by Avy2808** [comment]
@sritikamanjrekar can you please assign this issue to me. I would like to contribute to this
