### ISSUE TITLE
Contributing to this Repo

### ISSUE THREAD

**Issue by sona-123** [sritikamanjrekar/Print-Hacktoberfest2022#59]
I want to contribute to this repository under Hacktoberfest-2022

**Comment by Yashmittal01** [comment]
please assign it to me

**Comment by sharyu04** [comment]
can you please assign this to me under hacktoberfest2022

**Comment by Umang3072** [comment]
Can you please assign this to me ???

**Comment by sritikamanjrekar** [comment]
> Can you please assign this to me ???

YES

**Comment by falguni300103** [comment]
Can you please assign this issue to me? @sritikamanjrekar

**Comment by Avy2808** [comment]
@sritikamanjrekar can you please assign this issue to me. I would like to contribute to this

**Comment by Rishi0510** [comment]
Can you please assign me this issue to me ? @sritikamanjrekar
